### ISSUE TITLE
FC in GPM with XGPM 1.7

### ISSUE THREAD

**Issue by Gitoffthelawn** [Maxr1998/XGPM#1]
Hi. Thanks for this mod.

Tested XGPM 1.7 on Android 4.4.2 with GPM 6.2.2224U.

Enabled "Show My Library as Default Screen".  Ran GPM.  GPM now FC's.

Sorry, I wish I had more time to test, but unfortunately I have too many projects right now.

**Comment by Maxr1998** [comment]
I have some reports about FCs floating around at the moment, I will release a new version with a fix soon. Stay tuned.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by Maxr1998** [comment]
Did you try version 1.8 which I released yesterday evening?

**Comment by Gitoffthelawn** [comment]
I recently noticed a new version was released, but the changelog in the Xposed installer did not mention anything about relevant changes... so I didn't try it.

I'm happy to give it a try, if you like.

**Comment by Gitoffthelawn** [comment]
v1.8:
I tried the "Show My Library..." toggle, but it did not work.
I tried the "Show three column..." toggle, but I noticed no difference.

Nothing crashed, which was good.

**Comment by Maxr1998** [comment]
Try 1.8.2 again, please. :)
