### ISSUE TITLE
Request: Allow desktop-like sort functionality for playlists

### ISSUE THREAD

**Issue by AskAlice** [Maxr1998/XGPM#3]
One of the major shortcomings that I have noticed in the google play music app is that you can't sort the playlists like you can on the desktop site. On desktop it is possible to sort by #, name, duration, artist, album, number of plays, and thumbs up/down. I like to play my large, >500 track playlist sorted by track number (descending), which is not possible on the app.

I'm only lightly experienced with android studio, and not at all experienced with xposed. I will see what I can do to make this happen, but I will probably fail due to my lack of experience. Would be nice if someone else has interest in making this happen because I have no idea what I'm doing.

**Comment by Maxr1998** [comment]
I already have this feature on my list, I'll add it when I have time and motivation to dive into it :)
