### ISSUE TITLE
No album covers

### ISSUE THREAD

**Issue by GautierLePire** [Maxr1998/XGPM#4]
Album covers don't display on TrackSelector.
Screenshots : http://m.imgur.com/a/11qef

Also, GPM notification doesn't match material color palette, is there a way to make it material white/match album cover?

**Comment by thegeeex** [comment]
Screenshots : http://m.imgur.com/a/11qef

Also, GPM notification doesn't match material color palette, is there a way to make it material white/match album cover ?

Thank you in advance

**Comment by Maxr1998** [comment]
Thanks, I'll take a look at it.
The dark background is not an GPM issue, it's default for media notifications in AOSP.

**Comment by Massi-X** [comment]
Probably fixed in next version, you can try it on xda thread. http://forum.xda-developers.com/xposed/modules/mod-xgpm-google-play-music-mods-t3083542/page53

**Comment by GautierLePire** [comment]
Fixed! Thank you very much
