### ISSUE TITLE
Progress bar on notification

### ISSUE THREAD

**Issue by XtraordinairDEV** [Maxr1998/XGPM#5]
I would like to request a progress bar added to the GPM notification following the duration of the song.

**Comment by Maxr1998** [comment]
You can check out the module GPM notification seekbar, it's on Xposed repo and does exactly that. It's compatible with my module and I'm using it myself.

**Comment by XtraordinairDEV** [comment]
What version of GPM are you using? Not working for me.

**Comment by Maxr1998** [comment]
@XtraordinairDEV 6.8.2817A, I think

**Comment by XtraordinairDEV** [comment]
It works, I'm a dumbass. I know this wansnt really your mod but thanks for the help.

**Comment by Gitoffthelawn** [comment]
@XtraordinairDEV Don't feel bad.  We all take a drive down Dumbass Lane once in a while.  :-)

**Comment by Maxr1998** [comment]
@XtraordinairDEV Sure, glad it works now :) @Gitoffthelawn true :D
