### ISSUE TITLE
Issues since GPM 6.12

### ISSUE THREAD

**Issue by JaredTamana** [Maxr1998/XGPM#7]
Since the 6.12 update, the voice command buttons do not show up. Enabling XGPM's player layout will FC Google Play Music. Disabling lists from the hamburger menu also does not work. I'm sure there's more, but those are the things I noticed.

**Comment by Maxr1998** [comment]
@JaredTheWolf Update your GPM and XGPM, these issues were fixed. Voice commands were removed again by Google.
