### ISSUE TITLE
Request: Possibly add Tinted Status bar, and fix the artist name being cropped

### ISSUE THREAD

**Issue by classiccomplexity** [Maxr1998/XGPM#8]
[XGPM Mockup](http://i.imgur.com/jDCSt9i.jpg)

I made a mockup of the changes in photoshop with the before and after. I think adding the tinted status bar along with fixing the artist name from being cut in half would make the app look cleaner. Thank you so much for developing XGPM!

**Comment by Maxr1998** [comment]
Thanks, I wanted to fix this for a long time already, I'll take a look at it!

**Comment by Maxr1998** [comment]
Btw, the first part of this is a duplicate of #2.

**Comment by Maxr1998** [comment]
Fixed with 695156cca290415d3b5b0495b79c129ef3f3fa7b. Statusbar tinting will stay in #2.
